### PR TITLE
Extend Block Configuration

### PR DESCRIPTION
**Pull request by alex0412**
- configuration options for each field to display it's label and/or placeholder, also override default label/placeholder text, submit text
- add source field so one can identify where the registration came from
- add privacy and opt-in settings on block level, with a selection if they should be required, optional or completely off, independently of each other

### CODE REVIEW

**Comment by alex0412** [comment]
Left To Dos:
- add update hook to update existing block configurations, so that they don't break
- add update hook to remove global "hm_displayed_agreements" setting
- fix indenting (2 spaces)

Nice to have:
- move error messages from hardcoded into twig template to global config

**Comment by mtodor** [comment]
@alex0412 changes in 9783930 and 2476cb6:
- fixed some issue in JS when expanding of details is triggered (I guess problem is introduced with merging of code)
- fixed issue with title as variable name in template (looks like it's reserved), problem was thrown user error -> can be reproduced with opening newsletter page after cache clear
- checked properties with documentation and found in PDF doc, that "zip_code" is used instead of "postalcode", so that's also changed
- some small refactoring
- and additional coding style adjustments

That's all I think.

**Comment by alex0412** [comment]
@mtodor everything seems to work fine.

**Comment by mtodor** [comment]
I have also additionally tested update and it looks good.

From my point of view, this PR can be merged.

**Pull request merged**
